version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: app_frontend
    command: npm start
    #command: tail -f /dev/null
    volumes:
      - ./frontend/granada-front/:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: app_backend
    command: python3 manage.py runserver 0.0.0.0:8043
    volumes:
      - ./backend/analyzer:/usr/src/app
    ports:
      - "8043:8043"
    env_file:
      - ./backend/.env

  db:
    image: postgres:latest
    container_name: app_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: app_pgadmin
    ports:
      - "5050:80"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db