version: '3.8'

services:
  app:
    build: .
    container_name: granada_app
    command: python3 manage.py runserver 0.0.0.0:8043
    volumes:
      - ./analyzer:/usr/src/app
    ports:
      - "8043:8043"
    env_file:
      - ./.env
  
  db:
    image: postgres:latest
    container_name: granada_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: granada_pgadmin
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db